<?php

/**
 * @file
 * Module that allows you to link fields.
 */

/**
 * Function to gather supported field formatters.
 */
function linked_field_supported_formatters() {
  $formatters = array(
    'image',
    'text_plain',
  );

  // Allow other modules to alter the supported fields.
  drupal_alter('linked_field_supported_formatters', $formatters);

  return $formatters;
}

/**
 * Implements hook_field_formatter_info_alter().
 */
function linked_field_field_formatter_info_alter(&$info) {
  $supported = linked_field_supported_formatters();

  foreach ($supported as $s) {
    $info[$s]['settings']['linked'] = FALSE;
    $info[$s]['settings']['destination'] = '';
  }
}

/**
 * Implements hook_field_formatter_settings_summary_alter().
 */
function linked_field_field_formatter_settings_summary_alter(&$summary, $context) {
  $display = $context['instance']['display'][$context['view_mode']];
  $settings = $display['settings'];

  // Normalize the settings.
  $settings['linked'] = isset($settings['linked']) ? $settings['linked'] : FALSE;
  $settings['destination'] = isset($settings['destination']) ? $settings['destination'] : '';

  $supported = linked_field_supported_formatters();

  if (in_array($display['type'], $supported)) {
    if ($settings['linked'] && $settings['destination']) {
      $summary .= '<br />' . t('Linked to') . ': ' . $settings['destination'];
    }
    else {
      $summary .= ' ';
    }
  }
}

/**
 * Implements hook_field_formatter_settings_form_alter().
 */
function linked_field_field_formatter_settings_form_alter(&$settings_form, $context) {
  $field = $context['field'];
  $entity_type = $context['instance']['entity_type'];
  $display = $context['instance']['display'][$context['view_mode']];
  $settings = $display['settings'];

  $supported = linked_field_supported_formatters();

  $settings['linked'] = isset($settings['linked']) ? $settings['linked'] : FALSE;
  $settings['destination'] = isset($settings['destination']) ? $settings['destination'] : '';

  if (in_array($display['type'], $supported)) {
    $settings_form['linked_field'] = array(
      '#type' => 'container',
      '#attributes' => array('class' => array('linked-field-linked-wrapper')),
      '#attached' => array(
        'css' => array(
          drupal_get_path('module', 'linked_field') . '/css/linked-field.css',
        ),
      ),
    );

    $settings_form['linked_field']['linked'] = array(
      '#title' => t('Link this field'),
      '#type' => 'checkbox',
      '#default_value' => $settings['linked'],
    );

    $settings_form['linked_field']['destination'] = array(
      '#title' => t('Destination'),
      '#type' => 'textfield',
      '#default_value' => $settings['destination'],
      // @TODO: Add validation function which checks whether
      // linked field is checked.
      //'#required' => TRUE,
      '#element_validate' => array('token_element_validate'),
      '#description' => t('Here you can enter a token which will be used as link url.'),
      '#states' => array(
        'visible' => array(
          'input[name="fields[' . $field['field_name'] . '][settings_edit_form][settings][linked_field][linked]"]' => array('checked' => TRUE),
        ),
      ),
    );

    $settings_form['linked_field']['token'] = array(
      '#type' => 'container',
      '#children' => theme('token_tree', array('token_types' => array($entity_type))),
      '#states' => array(
        'visible' => array(
          'input[name$="fields[' . $field['field_name'] . '][settings_edit_form][settings][linked_field][linked]"]' => array('checked' => TRUE),
        ),
      ),
    );
  }
}

/**
 * Implements hook_field_attach_view_alter().
 */
function linked_field_field_attach_view_alter(&$output, $context) {
  foreach (element_children($output) as $field_name) {
    $supported = linked_field_supported_formatters();

    if (in_array($output[$field_name]['#formatter'], $supported)) {
      $element = &$output[$field_name];
      $instance = field_info_instance($element['#entity_type'], $field_name, $element['#bundle']);
      $display = isset($instance['display'][$context['view_mode']]) ? $instance['display'][$context['view_mode']] : $instance['display']['default'];
      $settings = $display['settings'];

      // Normalize the settings.
      $settings['linked'] = isset($settings['linked']) ? $settings['linked'] : FALSE;
      $settings['destination'] = isset($settings['destination']) ? $settings['destination'] : '';

      // If the destination field isn't filled for this field, we shouldn't
      // do anything. Continue to the next field.
      if (!$settings['destination']) {
        continue;
      }

      // Wrapping the source element into a link.
      $element = array(
        '#theme' => 'link',
        '#text' => drupal_render($element),
        '#path' => token_replace($settings['destination'], array($element['#entity_type'] => $element['#object'])),
        '#options' => array(
          'attributes' => array(),
          'html' => TRUE,
        ),
      );
    }
  }
}
